trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'


steps:

- task: UseDotNet@2
  displayName: "Get .NET SDK"
  inputs:
    packageType: 'sdk'
    version: '3.1.100'

- script: dotnet tool install --global Cake.Tool
  displayName: 'Install Cake tool'

- script: dotnet cake --artifacts=$(Build.ArtifactStagingDirectory)
  displayName: "Build project"

- task: PublishBuildArtifacts@1
  displayName: "Publish artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: "Push to test feed"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f9781677-d662-4f25-be5a-7763dd768c21'
