trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

name: $(version)+$(Build.SourceVersion)

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/MyProject.sln'
    arguments: '-c $(buildConfiguration) -p:Version=$(Build.BuildNumber)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/MyLibrary/MyLibrary.csproj'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/MyConsole/MyConsole.csproj'
    arguments: '--no-build -c $(buildConfiguration)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'