trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'


steps:

- task: UseDotNet@2
  displayName: "Get .NET SDK"
  inputs:
    packageType: 'sdk'
    version: '3.1.101'

- script: dotnet tool install --global Cake.Tool
  displayName: 'Install Cake tool'

- script: dotnet cake --target=Create-TestRelease --artifacts=$(Build.ArtifactStagingDirectory)
  displayName: "Build, test and pack"

- task: PublishTestResults@2
  displayName: "Publish test results"
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: 'TestResults'
    failTaskOnFailedTests: true
    publishRunAttachments: false

- task: PublishCodeCoverageResults@1
  displayName: "Publish code coverage"
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'TestResults/coverage/Cobertura.xml'
    failIfCoverageEmpty: true

- task: PublishBuildArtifacts@1
  displayName: "Publish artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'
