trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

# name: $(version)+$(Build.SourceVersion)

steps:

- task: UseDotNet@2
  displayName: "Get .NET SDK"
  inputs:
    packageType: 'sdk'
    version: '3.1.100'

- script: dotnet tool install --global Cake.Tool
  displayName: 'Install Cake tool'

- script: dotnet cake
  displayName: "Build project"

- task: DotNetCoreCLI@2
  displayName: "Pack libraries"
  inputs:
    command: 'pack'
    packagesToPack: 'src/MyLibrary/MyLibrary.csproj'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  displayName: "Prepare applications"
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/MyConsole/MyConsole.csproj'
    arguments: '--no-build -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: "Publish artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: "Push to test feed"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f9781677-d662-4f25-be5a-7763dd768c21'
